# Generated by Django 3.2.8 on 2022-04-07 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_type', models.CharField(choices=[('Complete', 'COMPLETE'), ('Scheduled', 'SCHEDULED'), ('Processing', 'PROCESSING'), ('Cancelled', 'CANCELLED')], default='Processing', max_length=20)),
            ],
        ),
    ]
