# Generated by Django 3.2.8 on 2022-04-11 19:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0001_initial'),
        ('appointment_status', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=999)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=20)),
                ('zip_code', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('email_address', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=20)),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('description', models.CharField(max_length=3000)),
                ('electrician_id', models.IntegerField()),
                ('appointment_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment_status.appointmentstatus')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
