# Generated by Django 3.2.8 on 2022-04-07 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='electrician_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
