# Generated by Django 3.2.8 on 2022-04-17 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='service',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='end',
            field=models.DateTimeField(default='2022-04-17 16:44:20'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='start',
            field=models.DateTimeField(default='2022-04-17 16:44:20'),
        ),
    ]
