# Generated by Django 3.2.8 on 2022-04-17 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_auto_20220417_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='end',
            field=models.DateTimeField(default='2022-04-17 18:22:21'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='start',
            field=models.DateTimeField(default='2022-04-17 18:22:21'),
        ),
    ]
