# Generated by Django 3.2.8 on 2022-04-13 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end',
            field=models.DateField(default='2022-04-12T23:40:36'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start',
            field=models.DateField(default='2022-04-12T23:40:36'),
        ),
    ]
