# Generated by Django 3.2.8 on 2022-04-07 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_appointment_electrician_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_date_time',
            field=models.CharField(default=0.00028260562385191464, max_length=255),
            preserve_default=False,
        ),
    ]
