# Generated by Django 3.2.8 on 2022-04-08 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_appointment_appointment_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='address',
            field=models.CharField(default='1915 Olive Street', max_length=999),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='city',
            field=models.CharField(default='St. Louis', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='email_address',
            field=models.CharField(default='pryor.matthew.a@gmail.com', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='first_name',
            field=models.CharField(default='Matt', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='last_name',
            field=models.CharField(default='Pryor', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='phone_number',
            field=models.CharField(default='123-456-7899', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='zip_code',
            field=models.CharField(default='63103', max_length=255),
            preserve_default=False,
        ),
    ]
