# Generated by Django 3.2.8 on 2022-04-08 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_auto_20220408_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='state',
            field=models.CharField(default='MO', max_length=20),
            preserve_default=False,
        ),
    ]
