# Generated by Django 3.2.8 on 2022-04-11 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_appointment_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='appointment_date_time',
        ),
        migrations.AddField(
            model_name='appointment',
            name='appointment_end_date',
            field=models.DateField(default='2022-04-27'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='appointment_start_date',
            field=models.DateField(default='2022-04-07'),
            preserve_default=False,
        ),
    ]
