# Generated by Django 3.2.8 on 2022-04-11 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_auto_20220411_1050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='service',
            new_name='title',
        ),
    ]
