# Generated by Django 3.2.8 on 2022-04-11 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_rename_service_appointment_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='appointment_end_date',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='appointment_start_date',
            new_name='start',
        ),
    ]
