# Generated by Django 3.2.8 on 2022-04-07 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('Employee', 'EMPLOYEE'), ('Customer', 'CUSTOMER')], default='Customer', max_length=20)),
            ],
        ),
    ]
