# Generated by Django 3.2.8 on 2022-04-17 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_or_employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertype',
            name='credentials',
            field=models.CharField(default='Certified with the St. Louis County Board of Electrical Examiners 2022 and the St. Louis County Dept. of Public Works', max_length=1000),
            preserve_default=False,
        ),
    ]
